# Reads the data file of COVID-19 cases in Vo'
# creates a graph file, to be displayed using Gephi or other graph visualisation software
# the input data file full_data.rds is the result of italy_cleaning_script.R 
# applied to anonymised_data_public_final.xlsx
# both from  https://github.com/ncov-ic/SEIR_Covid_Vo

library(magrittr)
library(rgexf)
library(igraph)  # graph creaation, export and displaying



rm(list = ls())
#a =  readxl::read_excel("data/anonymised_data_public_final.xlsx", sheet = 1, guess_max = 2900)
a = readRDS("../data/full_data.rds")  # the file generated by italy_cleaning_data_script.R din XLSX

print( a$symptomatic_at_any_time )
print( summary( a$symptomatic_at_any_time ) )
print( summary( a$symptomatic_at_first_sampling ) )
print( summary( a$symptomatic_at_follow_up ) )


nume = c("id",
"household_id",
"age_group",
"gender",
"fever",
"fever_temperature",
"cough",
"sore_throat",
"malaise",
"headache",
"diarrhea",
"conjunctivitis",
"other_symptoms",
"symptomatic_at_first_sampling",
"symptomatic_at_follow_up",
"symptomatic_at_any_time",
"positive",
"hospitalized",
"deceased",
"first_symptoms_date",
"clinical_condition_at_hospitalization")


# positive, symptomatic at any time, hostpitalized, clinical condition at hospitalize => scala


d = a[nume]
m = a[17:107] # the contact matrix
nm = names(m)
nd = d$id


# ---------------------- creaza o coloana (d$posi) 
# combinand d$positive si d$symptomatic, 
# ca sa se poata colora in graf si oamenii cu simptome, dar COVID negativi 

sum(as.integer(d$positive == "TRUE"))
sum(as.integer(d$symptomatic_at_any_time == "yes"))

v = paste(d$positive,d$symptomatic_at_any_time)
v[v == "FALSE no"] = "neg_asimpt"
v[v == "FALSE yes"] = "neg_simpt"
v[v == "TRUE no"] = "poz_asimpt"
v[v == "TRUE yes"] = "poz_simpt"
v = as.factor(v)
d$posi = v
print(summary(d$posi))






# ----- eliminam din matricea contactelor m pe strainii de sat (nu apar in a$id)
v = numeric(length(nm))
for (i in 1:length(nm)){
  t = which(nd == nm[i])
  if (length(t) == 0){
    v[i] = 0
  }
  else{
    v[i] = t
  }
}
vi = which(v>0)
#nm[which(vi == 0)]  # strainii de sat, + 3 "places"
print(v)
print('')
print(which(v == 0))
print(nm[vi])

print(dim(m))
m = m[vi]
print(dim(m))

nm = names(m)   # update dupa modificarea lui m
nd = d$id




# --------- elimina din d si din m (lin si col) pacientii din m care de fapt nu sunt pozitiv 
# (se pare ca exista acest paradox)
vd = which (nd %in% nm)  # indexurile pacientilor in lista tuturor oamenilor
print( sort(nd[vd]))
print( as.factor(sort(nm)) )

print('')
print( d$id[which (nd %in% nm)] )
print( d$positive[which (nd %in% nm)] )

vx = which ( (nd %in% nm) & (d$positive == F) ) 
nx = d$id[vx]
print( nx )


print(dim(d))
d = d[-vx,]
nd = d$id  # update
print(dim(d))


print(dim(m))
m = m[-vx,]
print(dim(m))

print( nm[which(nm %in% nx)] )
ox = which(nm %in% nx)
print(ox)

print(dim(m))
m = m[-ox]
nm = names(m)  # update
print(dim(m))

print( "Trebuie sa fie toate TRUE")
print( nm %in% nd )




# # -----elimina din d si din m (lin) oamenii care nu au avut contacte cu pacientii pozitivi
# 
# for (x in names(m)){
#   m[x] = as.integer(as.character(m[[x]]))
# 
# }
# 
# su = rowSums(m, na.rm=T)
# su = unname(su)
# print(sort(su, decreasing = T))
# #sf = as.factor(su[su>0])
# #plot(sf)  # face histograma
# 
# # aici este punctul CENTRAL, vectorul vsc cu cei care sunt scosi pentru ca nu sunt contacte etc.
# # vector de indecsi cu oamenii fara contacte cu pacientii --------
#      vsc = which(su == 0 & d$positive == F)
# # vector de indecsi cu oamenii fara contacte cu pacientii SI fara simptome - DE VAZUT
# #      vsc = which(su == 0 & d$posi == "neg_asimpt") 
# 
# print( length(vsc) )
# 
# print(nd[-vsc])
# print(dim(d))
# d = d[-vsc,]
# print(dim(d))
# d$id = factor(d$id)  # scoate leveluri care nu mai exista din factor
# nd = d$id  # update
# 
# print(dim(m))
# m = m[-vsc,]
# print(dim(m))
# nm = names(m)   # update
# 
# print(as.integer(d$positive == T))
# 
# print( " Trebuie toate TRUE")
# print( nm %in% nd )





# ------------- inlocuire in matricea contactelor
# era 1 direct, 2 indirect, 3 household
# va fi 1 indirect, 2 direct, 3 household (ptr. weight)

print( length(which( m==1 )) )
print( length(which( m==2 )) )
print( length(which( m==3 )) )

m[m == 1] = 11
m[m == 2] = 22
m[m == 11] = 2
m[m == 22] = 1

print( length(which( m==1 )) )
print( length(which( m==2 )) )
print( length(which( m==3 )) )





# ========================================================================




# ------------ creza index, pentru d - vertical, si pentru m - orizontal
nlin = dim(d)[1]
d$dindex = 1:nlin
#dindex = 1:nlin
print( d$index )
mindex = which(nd %in% nm)   # indexurile pacientilor in lista oamenilor

# ---------- creaza lista de edge-uri pentru graf din matricea de adiacenta

e = data.frame("")  # edge-uri

nlin = dim(m)[1]
ncol = dim(m)[2]
surs = integer(0)
dest = integer(0)
weig = integer(0)
for( i in 1:nlin ){
  for ( j in 1:ncol){
    if ( m[i,j] %in% c(1,2,3) ) {
      surs = c( surs, i );
      dest = c( dest, mindex[j] );
      weig = c( weig, m[i,j] )
    }
  }
}

ee = data.frame(surs, dest, weig)
ord = c(length(names(d)), 1:length(names(d))-1)
vv = d[,ord]   # pune indexul pe prima coloana, asa trebuie pentru vertexuri

g = graph_from_data_frame(ee, directed=FALSE, vertices=vv)



# ---------- creates the graph file, GRAPHML format appears to be the best for export from igraph
# fisier = "graf_temp"
fisier = "../graph/graph_file"
# format = "gml"
formatf = "graphml"    # asta vede mai bine 
fisier = paste(fisier, formatf, sep = '.')
print( fisier )
write.graph(graph = g, file = fisier, format = formatf)

# --- plots the graph directly from R, using colors for node status
#V(g)$color = d$posi
#V(g)$color = rainbow(4)[d$posi]
#plot(g, vertex.size = 5)

